const project = [
  {
    id: "1",
    category: "Html",
    image: "./image/about-me.png",
    name: "About me",
    github: "https://github.com/fmg-dev/about-me",
    demo: "https://fmg-dev.github.io/about-me/",
  },
  {
    id: "2",
    category: "Html",
    image: "./image/firstProject.png",
    name: "First Project",
    github: "https://github.com/fmg-dev/firstProject",
    demo: "https://fmg-dev.github.io/firstProject/index.html",
  },
  {
    id: "3",
    category: "Html",
    image: "./image/google-1998.png",
    name: "Google 1998",
    github: "https://github.com/fmg-dev/Google-1998",
    demo: "https://fmg-dev.github.io/Google-1998/",
  },
  {
    id: "4",
    category: "Html",
    image: "./image/araba-ilanı.png",
    name: "Araba ilanı",
    github: "https://github.com/fmg-dev/araba_ilani",
    demo: "https://fmg-dev.github.io/araba_ilani/",
  },
  {
    id: "5",
    category: "Html",
    image: "./image/practice.png",
    name: "Practice",
    github: "https://github.com/fmg-dev/Pratik",
    demo: "https://fmg-dev.github.io/Pratik/",
  },
  {
    id: "6",
    category: "Html",
    image: "./image/music-shop.png",
    name: "Music shop",
    github: "https://github.com/fmg-dev/muzikci",
    demo: "https://fmg-dev.github.io/muzikci/",
  },
  {
    id: "7",
    category: "Html",
    image: "./image/medium.png",
    name: "Meduim clone",
    github: "https://github.com/fmg-dev/medium",
    demo: "https://fmg-dev.github.io/medium",
  },
  {
    id: "8",
    category: "Html",
    image: "./image/blog.png",
    name: "Blog",
    github: "https://github.com/fmg-dev/blog",
    demo: "https://fmg-dev.github.io/blog",
  },
  {
    id: "9",
    category: "JavaScript",
    image: "./image/kilo.png",
    name: "Kilo indeksi",
    github: "https://github.com/fmg-dev/kilo-indeksi",
    demo: "https://fmg-dev.github.io/kilo-indeksi/",
  },
  {
    id: "10",
    category: "JavaScript",
    image: "./image/counter.png",
    name: "Counter",
    github: "https://github.com/fmg-dev/Counterlast",
    demo: "https://fmg-dev.github.io/Counterlast/",
  },
  {
    id: "11",
    category: "JavaScript",
    image: "./image/city-plate.png",
    name: "City plate",
    github: "https://github.com/fmg-dev/City-Plate",
    demo: "https://fmg-dev.github.io/City-Plate/",
  },
  {
    id: "12",
    category: "react",
    image: "./image/business-card.png",
    name: "Business card",
    github: "https://github.com/fmg-dev/businesscard",
    demo: "https://fmg-dev.github.io/businesscard",
  },
  {
    id: "13",
    category: "react",
    image: "./image/travel-journal.png",
    name: "Travel Journal",
    github: "https://github.com/fmg-dev/traveljournal",
    demo: "https://fmg-dev.github.io/traveljournal/",
  },
  {
    id: "14",
    category: "react",
    image: "./image/react-city-plate.png",
    name: "React city plates",
    github: "https://github.com/fmg-dev/react-city-plates",
    demo: "https://fmg-dev.github.io/react-city-plates",
  },
  {
    id: "15",
    category: "react",
    image: "./image/fmgco.png",
    name: "FMGCO",
    github: "https://github.com/fmg-dev/FMGCO",
    demo: "https://fmg-dev.github.io/FMGCO",
  },
  
];

export default project;
